name: Deploy

# Concurrency ensures only one run of the workflow is happening at a time.
concurrency: deploy

on:
  push:
    branches:
      - master

env:
  SANITY_PROJECT_ID: todo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        env:
          cache-name: cache-rust
          prefix: v0-${{ runner.os }}
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ env.prefix }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.prefix }}-${{ env.cache-name }}-
            ${{ env.prefix }}-

      - name: Sanity Install
        run: cargo install sanity-cli

      - name: Sanity Login
        run: |
          sanity --base-api-url https://web-tb546tjmbq-uc.a.run.app/api/v0/ login --token ${{ secrets.SANITY_TOKEN }}

      - name: Push to Sanity
        run: |
          sanity --base-api-url https://web-tb546tjmbq-uc.a.run.app/api/v0/ push web/Dockerfile $SANITY_PROJECT_ID/web
